apiVersion: cloudnativetoolkit.dev/v2
kind: Solution
metadata:
  name: cloud-pak-for-security-openshift
  labels:
    type: infrastructure
    platform: ibm
    flavor: standard
  annotations:
    displayName: 'Software: IBM Cloud Pak for Security'
    description: Automation to deploy IBM Cloud Pak for Security on Top of RedHat OpenShift
spec:
  version: v1.0.1
  stack:
    - name: 105-existing-openshift
      layer: infrastructure
      description: Existing OpenShift cluster
      version: v1.0.1
    - name: 200-openshift-gitops
      layer: software
      description: >-
        Provisions OpenShift GitOps (ArgoCD) into an existing cluster and
        bootstraps it to a gitops repository
      version: v1.0.1
    - name: 700-cp4s-multicloud
      layer: software
      description: >-
        Populates a GitOps repository with the components of IBM Cloud Pak for
        Security
      version: v1.0.2
  variables:
    - name: cluster_ingress_subdomain
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
    - name: config_banner_text
      type: string
      description: The text that will appear in the top banner in the cluster
    - name: entitlement_key
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
    - name: gitops-cp4s_admin_user
      type: string
      description: >-
        Short name or email-id of the user to be given administrator privileges
        in the default account. Mandatory value while creating
        cp4s-threat-management-instance
      sensitive: true
    - name: gitops-cp4s_roks_auth
      description: >-
        Whether ROKS (RedHat OpenShift on IBM Cloud) authentication need to be
        enabled (true|false)
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      value: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      value: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      value: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      value: ''
      sensitive: true
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      value: ''
